# NOTE:

1. Please implement the TFIDf function such that for each word in a sentence, its corresponding tfidf value is assigned. Thus a 4 x 6 sized matrix should be returned where the rows represent sentences and the columns represent words. We wish to keep it simple in the beginning.

2. In reality the TFIDF function should return a matrix where the rows represent sentences and the columns represent words (ie: Features). Every sentence vector in this matrix will be 'd' dimensional, where d = number of unique words in the corpus (ie: Vocabulary).
Every position/cell in a sentence vector correponds to a particular word in the vocabulary. If the word is not present in the current sentence, we assign a value of 0 to that cell, else we assign the TFIDF value.

# **Implement TF-IDF from scratch**

In this assignment, you will implement TF-IDF vectorization of text from scratch using only Python and inbuilt data structures. You will then verify the correctness of the your implementation using a "grader" function/cell (provided by us) which will match your implmentation.

The grader fucntion would help you validate the correctness of your code. 

Please submit the final Colab notebook in the classroom ONLY after you have verified your code using the grader function/cell.

**(FAQ) Why bother about implementing a function to compute TF-IDF when it is already available in major libraries?**

Ans.
1. It helps you improve your coding proficiency.
2. It helps you obtain a deeper understanding of the concepts and how it works internally. Knowledge of the internals will also help you debug problems better.
3. A lot of product based startups and companies do focus on this in thier interviews to gauge your depth and clarity of understanding along with your programming skills. Hence, most top universities have implementations of some ML algorithms/concepts as mandatory assignments.

**NOTE: DO NOT change the "grader" functions or code snippets written by us.Please add your code in the suggested locations.**

Ethics Code:
1. You are welcome to read up online resources to implement the code. 
2. You can also discuss with your classmates on the implmentation over Slack.
3. But, the code you wirte and submit should be yours ONLY. Your code will be compared against other stduents' code and online code snippets to check for plagiarism. If your code is found to be plagiarised, you will be awarded zero-marks for all assignments, which have a 10% wieghtage in the final marks for this course.

In [ ]:
# Corpus to be used for this assignment

corpus = [
     'this is the first document mostly',
     'this document is the second document',
     'and this is the third one',
     'is this the first document here',
]

In [ ]:
# Please implement this fucntion and write your code wherever asked. Do NOT change the code snippets provided by us.
import numpy as np
import math 

def computeTFIDF (corpus):
  """Given a list of sentences as "corpus", return the TF-IDF vectors for all the 
  sentences in the corpus as a numpy 2D matrix. 
  
  Each row of the 2D matrix must correspond to one sentence 
  and each column corresponds to a word in the text corpus. 
  
  Please order the rows in the same order as the 
  sentences in the input "corpus". 
    
  Ignore puncutation symbols like comma, fullstop, 
  exclamation, question-mark etc from the input corpus.
  
  For e.g, If the corpus contains sentences with these 
  9 distinct words, ['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this'], 
  then the first column of the 2D matrix will correpsond to word "and", the second column will 
  correspond to column "document" and so on. 
  
  Write this function using only basic Python code, inbuilt Data Structures and  NumPy ONLY.

  Implement the code as optimally as possible using the inbuilt data structures of Python.
  """

  ##############################################################
  ####   YOUR CODE BELOW  as per the above instructions #######
  ##############################################################
  def idf_calc(word) :
    '''
    To calculate the idf for each word
    '''
    mtch_count=0
    len_of_corpus=len(corpus)
    for doc in corpus :
      if word in doc :     
        mtch_count += 1 
    #print("for word " + word +" matching count is "+ str(mtch_count))  
    #clcualting the idf
    idf=math.log(((len_of_corpus/mtch_count)))
    #print("idf " + str(idf))
    return idf


  idffor_enttire_set=[]

  for i in corpus :
    idf_for_rec=[]
    #print(i)
    lst_i= i.split()
    len_of_doc=len(lst_i)
    for word in lst_i :
          #print(word)
          count_ofmatcword=lst_i.count(word)
          tf = ((count_ofmatcword/len_of_doc))
          #idf_word=idf_calc(word)
          #print(tf)
          idf_word=idf_calc(word)
          tf_idf=round(((tf*idf_word)),2)
          idf_for_rec.append(tf_idf)
    idffor_enttire_set.append(idf_for_rec)

  np_aray = np.array(idffor_enttire_set) 
  return np_aray
  



In [ ]:
import numpy as np
X_custom = computeTFIDF(corpus)
print(X_custom)

[[0.   0.   0.   0.12 0.05 0.23]
 [0.   0.1  0.   0.   0.23 0.1 ]
 [0.23 0.   0.   0.   0.23 0.23]
 [0.   0.   0.   0.12 0.05 0.23]]


# Grader Cell
Please execute the following Grader cell to verify the correctness of your above implementation. This cell will print "Success" if your implmentation of the computeTFIDF() is correct, else, it will print "Failed". Make sure you get a "Success" before you submit the code in the classroom.

In [ ]:
###########################################
## GRADER CELL: Do NOT Change this.
# This cell will print "Success" if your implmentation of the computeTFIDF() is correct.
# Else, it will print "Failed"
###########################################
import numpy as np

# compute TF-IDF using the computeTFIDF() function
X_custom = computeTFIDF(corpus)

print(X_custom)

# Reference grader array - DO NOT MODIFY IT
X_grader = np.array(
    [[0, 0, 0, 0.12, 0.05, 0.23],
     [0, 0.1, 0, 0, 0.23, 0.1],
     [0.23, 0, 0, 0, 0.23, 0.23],
     [0, 0, 0, 0.12, 0.05, 0.23]]
     )
  

# compare X_grader and X_custom
comparison = ( X_grader == X_custom )
isEqual = comparison.all()

if isEqual:
  print("******** Success ********")
else:
  print("####### Failed #######")
  print("\nX_grader = \n\n", X_grader)
  print("\n","*"*50)
  print("\nX_custom = \n\n", X_custom)


[[0.   0.   0.   0.12 0.05 0.23]
 [0.   0.1  0.   0.   0.23 0.1 ]
 [0.23 0.   0.   0.   0.23 0.23]
 [0.   0.   0.   0.12 0.05 0.23]]
******** Success ********


below code is for calculating for 11 dimmensions, not for assignment submission

In [ ]:
import numpy as np
word_corpus=[]
for i in corpus :
  lst_i= i.split()
  for word in lst_i :
      word_corpus.append(word)
unique_nparay=np.unique(np.array(word_corpus))
unique_nparay



##############################################################
####  #calculating TF for unique keywordsthat is for all 11 dimmensions
##############################################################
#calculating TF in tf dictionary
import math

for key in unique_nparay :
  print(key)
  tf_val=[]
  cnt_match_doc=0
  for i in corpus :
     lst_i= i.split()
     lendoc=len(lst_i)
     lenalldoc=len(corpus)
     if key in lst_i:
       count =lst_i.count(key)
       cnt_match_doc =  cnt_match_doc+1
       print(lst_i)
       #print(lendoc)
       #print(count)
       tf=((count/lendoc))
       #print(tf)  
     else :
        count = 0
        tf=0        
     tf_val.append(tf)      
  print(cnt_match_doc)
  idfwo_log = ((lendoc/cnt_match_doc))
  idfwo=math.log(idfwo_log)
  print(idfwo_log)
  print(idfwo)
  print(type(tf_val))
  tf_valarry=np.array(tf_val)
  tf_dict[key]= tf_valarry*idfwo
print(tf_dict)

